git add .git
git add .gitignore
git add .ruby-version
git add Gemfile
git add Gemfile.lock
git add README.md
git add Rakefile
git add app
git add bin
git add config
git add config.ru
git add db
git add git_add.sh
git add lib
git add log
git add package.json
git add public
git add storage
git add test
git add tmp
